services:
  opensearch:
    container_name: opensearch
    image: opensearchproject/opensearch:1.1.0
    environment:
      - node.name=opensearch
      - cluster.name=opensearch-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_SECURITY_PLUGIN=true"
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/opensearch/data
  localstack:
      container_name: localstack
      image: localstack/localstack
      ports:
        - "4566:4566"
        - "4510-4559:4510-4559"
      depends_on:
        - opensearch
      environment:
        - SERVICES=dynamodb,opensearch
        - OPENSEARCH_CUSTOM_BACKEND=http://opensearch:9200
        - DEBUG=1
      volumes:
        - "./volume:/var/lib/localstack"
        - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  data01:
    driver: local