services:
  opensearch:
    image: opensearchproject/opensearch:3.1.0
    container_name: test-dynamo-opensearch
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.seed_hosts=opensearch-node1
      - cluster.initial_cluster_manager_nodes=opensearch-node1
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - DISABLE_SECURITY_PLUGIN=true
      - DISABLE_INSTALL_DEMO_CONFIG=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9201:9200"
      - "9601:9600"
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    networks:
      - opensearch-net

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:3.1.0
    container_name: test-dynamo-opensearch-dashboards
    ports:
      - "5602:5601"
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: true
    depends_on:
      - opensearch
    networks:
      - opensearch-net

  data-prepper:
    image: opensearchproject/data-prepper:2.8.0
    container_name: test-dynamo-data-prepper
    ports:
      - "4900:4900"
      - "21890:21890"
    volumes:
      - ./data-prepper/pipelines:/usr/share/data-prepper/pipelines
      - ./data-prepper/config:/usr/share/data-prepper/config
    environment:
      - JAVA_OPTS=-Xms512m -Xmx512m
    depends_on:
      - opensearch
      - localstack
    networks:
      - opensearch-net
      - localstack-net

  localstack:
    image: localstack/localstack:3.2.0
    container_name: test-dynamo-localstack
    ports:
      - "4567:4566"
    environment:
      - SERVICES=dynamodb,dynamodbstreams
      - DEBUG=0
      - DYNAMODB_SHARE_DB=1
      - DYNAMODB_IN_MEMORY=0
    volumes:
      - localstack-data:/var/lib/localstack
    networks:
      - localstack-net

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin:latest
    container_name: test-dynamo-dynamodb-admin
    ports:
      - "8002:8001"
    environment:
      - DYNAMO_ENDPOINT=http://localstack:4566
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    depends_on:
      - localstack
    networks:
      - localstack-net

volumes:
  opensearch-data:
    driver: local
  localstack-data:
    driver: local

networks:
  opensearch-net:
    driver: bridge
  localstack-net:
    driver: bridge
