dynamodb-cdc-pipeline:
  source:
    http:
      port: 21890
  buffer:
    bounded_blocking:
      buffer_size: 1024
      batch_size: 100
  processor:
    - add_entries:
        entries:
          - key: "source"
            value: "dynamodb"
          - key: "@timestamp"
            value: '${getMetadata("receivedTime")}'
  sink:
    - opensearch:
        hosts: ["http://opensearch:9200"]
        index: "dynamodb-cdc"
        insecure: true
        username: null
        password: null

dynamodb-stream-pipeline:
  source:
    dynamodb:
      aws:
        region: "us-east-1"
      tables:
        - table_arn: "arn:aws:dynamodb:us-east-1:000000000000:table/test-table"
          stream:
            start_position: "LATEST"
          export:
            s3_bucket: "data-prepper-export"
            s3_region: "us-east-1"
            s3_prefix: "export/"
  processor:
    - add_entries:
        entries:
          - key: "pipeline"
            value: "dynamodb-stream"
  sink:
    - opensearch:
        hosts: ["http://opensearch:9200"]
        index: "dynamodb-stream"
        insecure: true